// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDWzNqSM415WfLoFnX3iA3u2OMncp7pHE',
    appId: '1:218571899430:web:fababdf15e2e4e7101dce7',
    messagingSenderId: '218571899430',
    projectId: 'notevault1-7cd04',
    authDomain: 'notevault1-7cd04.firebaseapp.com',
    storageBucket: 'notevault1-7cd04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmBWgXlSJQvgeObOfeJET2tMOOfhd7Wt4',
    appId: '1:218571899430:android:b88d21011b6642e101dce7',
    messagingSenderId: '218571899430',
    projectId: 'notevault1-7cd04',
    storageBucket: 'notevault1-7cd04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY0IpG4tMJMgRhVlrl_oE8U7F0np5KrLE',
    appId: '1:218571899430:ios:99aa96064b256c6301dce7',
    messagingSenderId: '218571899430',
    projectId: 'notevault1-7cd04',
    storageBucket: 'notevault1-7cd04.appspot.com',
    iosBundleId: 'com.example.notevault1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY0IpG4tMJMgRhVlrl_oE8U7F0np5KrLE',
    appId: '1:218571899430:ios:99aa96064b256c6301dce7',
    messagingSenderId: '218571899430',
    projectId: 'notevault1-7cd04',
    storageBucket: 'notevault1-7cd04.appspot.com',
    iosBundleId: 'com.example.notevault1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDWzNqSM415WfLoFnX3iA3u2OMncp7pHE',
    appId: '1:218571899430:web:f60af14b55c3f70601dce7',
    messagingSenderId: '218571899430',
    projectId: 'notevault1-7cd04',
    authDomain: 'notevault1-7cd04.firebaseapp.com',
    storageBucket: 'notevault1-7cd04.appspot.com',
  );
}
